apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: oc-apply-deploymentconfig
spec:
  inputs:
    resources:
    - type: git
      name: k8s-repo
    - type: image
      name: new-image
    params:
    - name: manifest-directory
      description: The directory in source that contains yaml manifests
      type: string
      default: "k8s"
    - name: deploymentconfig-name
      description: The name of the deploymentconfig to patch the image to
      type: string
  steps:
  - name: apply
    image: quay.io/openshift/origin-cli:latest
    workingdir: /workspace/k8s-repo
    command: ["/bin/bash", "-c"]
    args:
    - |-
      echo Applying manifests in $(inputs.params.manifest-directory) directory
      oc apply -f $(inputs.params.manifest-directory)
      echo -----------------------------------
  - name: patch
    image: quay.io/openshift/origin-cli:latest
    command: ["/bin/bash", "-c"]
    args:
    - |-
        oc patch deploymentconfig $(inputs.params.deploymentconfig-name) \
         --patch='{
           "spec":{
             "template":{
               "spec":{
                 "containers":[{
                   "name": "$(inputs.params.deploymentconfig-name)",
                   "image":"$(inputs.resources.new-image.url)"
                 }]
               }
             }
           }
         }'
        oc rollout latest deploymentconfig/$(inputs.params.deploymentconfig-name)
