apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: findmyrelative-ui-pipeline
spec:
  resources:
  - name: source-git-repo
    type: git
  - name: image-resource-name
    type: image
  params:
  - name: deploymentconfig-name
    type: string
    description: name of the deploymentconfig to be patched
  tasks:
  - name: build-image
    taskRef:
      name: buildah-v0-8-0
      kind: ClusterTask
    resources:
      inputs:
      - name: source
        resource: source-git-repo
      outputs:
      - name: image
        resource: image-resource-name
    params:
    - name: TLSVERIFY
      value: "false"
  - name: create-upate-deploymentconfig
    taskRef:
      name: oc-apply-deploymentconfig
    resources:
      inputs:
      - name: k8s-repo
        resource: source-git-repo
      - name: new-image
        resource: image-resource-name
    params:
    - name: deploymentconfig-name
      value: frontend
    runAfter:
    - build-image
