apiVersion: v1
kind: Secret
metadata:
  name: findmyrelative-backend-webhook-secret
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
stringData:
  #https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token
  token: {{ .Values.backend.token }} # github auth token
  secret: {{ .Values.backend.secret }} # add-random string data
