{{ if .Values.pipelines.start }}
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: findmyrelative-backend-pipelinerun
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
spec:
  pipelineRef:
    name: findmyrelative-backend-pipeline
  resources:
  - name: source-git-repo
    resourceRef:
      name: findmyrelative-backend-git-repo
  - name: image-resource-name
    resourceRef:
      name: findmyrelative-backend-image
{{ end }}
