{{ if .Values.backend.token  }}
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: create-findmyrelative-backend-repo-webhook-run
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "7"
spec:
  taskRef:
    name: create-webhook
  inputs:
    params:
    - name: GitHubOrg
      value: {{ .Values.backend.github.org }}
    - name: GitHubUser
      value: {{ .Values.backend.github.user }}
    - name: GitHubRepo
      value: {{ .Values.backend.github.repo }}
    - name: GitHubSecretName
      value: findmyrelative-backend-webhook-secret
    - name: GitHubAccessTokenKey
      value: token
    - name: GitHubSecretStringKey
      value: secret
    - name: ExternalDomain
      value: http://findmyrelative-backend-cicd-eventlistener-find-my-relative.{{ regexReplaceAll ".*apps" .Values.clusterHostname "apps" }}

  timeout: 1000s
  serviceAccount: serviceaccount
{{ end }}
