apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: findmyrelative-backend-cicd-eventlistener
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "3"
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-findmyrelative-backend-cicd-listener
    weight: 100
status:
  ingress:
    - conditions:
      - lastTransitionTime: "2019-12-06T03:24:58Z"
        status: "True"
        type: Admitted
      host: ""
      routerCanonicalHostname: ""
      routerName: default
      wildcardPolicy: None
